baseURL = 'https://ai-code-terminal.dev/'
languageCode = 'en-us'
title = 'AI Code Terminal: The AI-Native Shell'

[params]
  description = 'A self-hosted development environment for the post-IDE era. Code from any device with a fast, lightweight, AI-native shell.'
  github_url = 'https://github.com/drmhse/ai-code-terminal'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
